robot_id: puffle
robot_type: go2
provider_id: puffle-go2
provider_key_root: argos

resources:
  - resource_id: arducam_001
    capabilities:
      - camera.rgb
      - camera.intrinsics
    topics:
      rgb: /arducam/image_rect
      camera_info: /arducam/camera_info_rect

  - resource_id: realsense_001
    capabilities:
      - camera.rgb
      - camera.rgbd
      - camera.intrinsics
    topics:
      rgb: /camera/realsense_001/color/image_raw
      depth: /camera/realsense_001/aligned_depth_to_color/image_raw
      camera_info: /camera/realsense_001/color/camera_info
    depth_scale: 0.001

  - resource_id: realsense_002
    capabilities:
      - camera.rgb
      - camera.rgbd
      - camera.intrinsics
    topics:
      rgb: /camera/realsense_002/color/image_raw
      depth: /camera/realsense_002/aligned_depth_to_color/image_raw
      camera_info: /camera/realsense_002/color/camera_info
    depth_scale: 0.001
